    <footer>
        <ul class="row col-12 bg-dark m-0">
            <li><a href="#" class="text-white">Mentions légales</a></li>
            <li><a href="#" class="text-white">Horaires</a></li>
            <li><a href="#" class="text-white">Plan du site</a></li>
        </ul>
    </footer>
    
    <script type="text/javascript" src="evaluation.js"></script>
    <script type="text/javascript" src="evaluation2.js"></script>
    <script type="text/javascript" src="delete.js"></script>
</body>
</html>