<main>
    <div class="d-flex">
        <div class="col-10">
            <h1 class="text-center">Liste des produits</h1>
        </div>
        <div class="col-2 text-center pt-3">
            <a href="ajout.php"><button class="btn btn-success">AJOUTER</button></a>
        </div>
    </div>
    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="bg-dark text-white">
                    <th scope="col">Photo</th>
                    <th scope="col">ID</th>
                    <th scope="col">Référence</th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Libellé</th>
                    <th scope="col">Prix</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Couleur</th>
                    <th scope="col-2">Ajout</th>
                    <th scope="col">Modif</th>
                    <th scope="col">Bloqué</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($produits as $produit) { ?>
                    <tr>
                        <td><img src="../jarditou_photos/<?php echo $produit->pro_id . '.' . $produit->pro_photo; ?>" alt="" class="img-fluid"></td>
                        <td><?php echo $produit->pro_id; ?></td>
                        <td><?php echo $produit->pro_ref; ?></td>
                        <td><?php echo $produit->cat_nom; ?></td>
                        <td><a href="detail.php?id=<?php echo $produit->pro_id; ?>"> <?php echo $produit->pro_libelle; ?> </a></td>
                        <td><?php echo $produit->pro_prix . '€'; ?></td>
                        <td><?php echo $produit->pro_stock; ?></td>
                        <td><?php echo $produit->pro_couleur; ?></td>
                        <td><?php echo $produit->pro_d_ajout; ?></td>
                        <td><?php echo $produit->pro_d_modif; ?></td>
                        <td><?php if ($produit->pro_bloque == 1) {
                                echo "Oui";
                            }; ?></td>
                    </tr>
                <?php }; ?>
            </tbody>
        </table>
    </div>
</main>