<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body class="container-fluid">
    <header>
        <div class="row">
            <img src="images/jarditou_logo.jpg" alt="logo jarditou" class="img-fluid col-6">
            <h3 class="col-6 text-center pt-5">La qualité depuis 70 ans.</h3>
        </div>
        <ul class="row col-12 bg-dark m-0">
            <li><a href="index.html" class="text-white">Accueil</a></li>
            <li><a href="tableau.html" class="text-white">Tableau</a></li>
            <li><a href="contact.html" class="text-white">Contact</a></li>
            <li><a href="evaluation.html" class="text-white">Evaluation</a></li>
        </ul>
        <img src="images/promotion.jpg" alt="promotion jarditou" class="row img-fluid col-12 p-0 m-0">
    </header>